<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
    ->prependStylesheet('https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css')
    ->prependStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons')
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    // ->prependStylesheet('https://use.fontawesome.com/releases/v5.15.4/css/all.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
    <!-- material desing -->
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/> -->
    <!-- <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> -->
</head>

<body>
    <div class="contenedor">
        <?= $this->content ?>
    </div>
    <!-- <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script> -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        // ->prependFile('https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js')
        ->prependScript('https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js')
        ->prependFile($this->basePath('js/app_material.js'))
        // ->prependFile($this->basePath("public\js\app_material.js"))
    ?>
</body>

</html>